name: Fetch Tuya Logs

on:
  schedule:
    - cron: "*/1 * * * *"  # every minute
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          echo "tinytuya" > requirements.txt
          pip install -r requirements.txt

      - name: Run fetch script
        env:
          TUYA_ACCESS_ID: ${{ secrets.TUYA_ACCESS_ID }}
          TUYA_ACCESS_KEY: ${{ secrets.TUYA_ACCESS_KEY }}
          TUYA_REGION: us
          TUYA_DEVICE_ID: ${{ secrets.TUYA_DEVICE_ID }}
        run: python fetch_logs.py

      - name: Commit and push if data changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest.json
          git diff --quiet && echo "No changes" || (git commit -m "Update logs $(date)" && git push)
